#ID of the phone item
ID: 405


#--------------------------------------------------------------------------------#

#You can use %player% only for those messages
INFO_FORMAT: "%prefix% %message%"
HOUR_FORMAT: "HH:mm:ss"
HOUR_MESSAGE: "&6&lTime: %hour%"

NO_ITEM: "&cYou must be holding a phone to do this! (ID:&e %id%&c)"


#--------------------------------------------------------------------------------#


#GUI Configuration
#You can use %target%, %caller% and colors codes

GUI:
    
    #Errors messages
    USE_ADD: "&cUse /add <player> [player2] [player3]... to add a player to your call."

    #Infos messages
    TYPE_YES: "&aType /answer %caller% to &eaccept&a."
    ENTER_A_MSG: "ยง6Type a message."
    ENTER_A_NAME: "ยง6Enter a name."
    ENTER_MULTIPLE_NAMES: "ยง6Enter multiple names."

#Call Configuration
#You can use %target%, %caller% and colors codes
#You can use %id% only in NO_ITEM message

CALL:
    
    PREFIX: "&8[&6&lCall&8]&r "
    FORMAT: "%prefix% %sender% &6->&7 %message%"

    #Errors messages
    USE_ADD: "&cUse /add <player> [player2] [player3]... to add players to your call."
    NOT_IN_CALL: "&cYou are not in call!"
    NOT_CALL_LEADER: "&cYou must be the call leader in order to do this!"
    CALLER_ALREADY_IN_CALL: "&cYou are already in a call!"
    TARGET_ALREADY_IN_CALL: "&e%target%&c is in a call right now!"
    CANT_CALL_YOURSELF: "&cYou cannot call yourself!"
    CANT_ADD_YOURSELF: "&cYou can't add yourself to the call!"
    CANT_END: "&cYou cannot end the call."

    #Infos messages
    TYPE_YES: "&aType /answer %caller% to &eaccept&a."
    TYPE_NO: "&aType /deny %caller% to &crefuse a call&a."
    CALLER_SEND_CALL: "&aNow calling&e %target%&a."
    TARGET_RECEIVE_CALL: "&e%caller%&a is caling you!"
    TARGET_RECEIVE_ADD: "&e%caller%&a is adding you to their call!"
    CALLER_OFFLINE: "&c%caller% is not online!"
    TARGET_OFFLINE: "&c%target% is not online!"
    NOT_CALLED_YOU: "&c%caller% is not calling you!"
    TARGET_ACCEPT_CALL: "&aYou have accepted the call from &e%caller%&a."
    CALLER_ACCEPT_CALL: "&e%target%&a has answered your call."
    TARGET_DENY_CALL: "&cYou have denied the call from &e%caller%&c."
    CALLER_DENY_CALL: "&e%target% &ca refused to answer your call."
    CALLER_ADD_TARGET: "&aYou are adding &e%target%&a to the call."
    TARGET_ADD: "&aYou have been added to a call by &e%caller%&a."
    QUIT_CALL: "&e%target%&a hung up."
    END_CALL: "&6&l%caller% ended the call."
    END_CALL_CALLER: "&6&lYou have ended the call."


#--------------------------------------------------------------------------------#


#SMS Configuration
#You can use %target%, %sender% and colors codes
#You can use %sms% only in PRINT_LIST message
SMS:

    PREFIX: "&8[&6&lSMS&8]&r "
    FORMAT_CALLER: "%prefix% Me &6->&7 %target%: %message%"
    FORMAT_TARGET: "%prefix% %sender% &6->&7 Me: %message%"

    #Errors messages
    TARGET_OFFLINE: "&c%target% is offline!"
    CANT_LOAD: "&cYou have never sent a message to &e%target%"
    
    #Infos messages
    SMS_SEND: "&aYou sent a message to &e%target%&a !"
    SMS_RECEIVE: "&aYou have received an SMS from &e%sender&a !"
    ANNOUNCE_LIST: "&6&lYour message history with %target%: "
    SMS_LIST: "&7%sms%"
