name: HavenPhone
author: TheCodeCrafter
version: 0.1.0
main: net.fathomtech.plugins.CityPlus.Main
commands:
  havenphone:
    description: Show HavenPhone infos.
  call:
    description: Start a call.
  answer:
    description: Accept a call.
  deny:
    description: Deny a call.
  add:
    description: Add a player to your call.
  global:
    description: Speak in global chat during a call.
  hangup:
    description: Leave the call.
  stopcall:
    description: Stop the call.
  sms:
    description: Send a SMS.
  smslist:
    description: See a list of your SMS.
    aliases: [smsliste]
  hour:
    description: Show the real time.
